project_name: Matplotlib Scalebar
repository_url: https://github.com/kolibril13/plywood-gallery-matplotlib-scalebar
user_content_version:  0.8.1 (Matplotlib Scalebar) #  Note: this is NOT the version of the plywood gallery, but the version of the plywood content.
description: |
   Cheat sheet made with https://github.com/kolibril13/plywood-gallery
favicon: icon.png # prefered resolution : 48x48 pixel
preview_image: https://kolibril13.github.io/plywood-gallery-matplotlib-scalebar/preview_image.png # prefered resolution 600x315, must be an url
gallery_parameters_path: gallery_assets/gallery_parameters.json